import { createServerFn } from "@tanstack/react-start";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

/**
 * Called by the dashboard when a user visits /dashboard/linking?token=...
 * The token was generated by the bot when the user ran /link or h!link.
 * This attaches the Clerk user ID to the pre-created row.
 */
export const claimBotToken = createServerFn({ method: "POST" })
  .inputValidator((input: { token: string; clerkUserId: string }) => {
    if (!input?.token || !input?.clerkUserId) throw new Error("token and clerkUserId are required");
    return input;
  })
  .handler(async ({ data }) => {
    const { data: row, error: fetchErr } = await supabaseAdmin
      .from("discord_links")
      .select("*")
      .eq("verification_code", data.token)
      .maybeSingle();

    if (fetchErr) throw new Error(fetchErr.message);
    if (!row) return { ok: false, reason: "not_found" } as const;
    if (row.verified) return { ok: false, reason: "already_used" } as const;
    if (row.expires_at && new Date(row.expires_at).getTime() < Date.now()) {
      return { ok: false, reason: "expired" } as const;
    }

    const { error: updateErr } = await supabaseAdmin
      .from("discord_links")
      .update({
        clerk_user_id: data.clerkUserId,
        verified: true,
        verification_code: null,
        expires_at: null,
        linked_at: new Date().toISOString(),
      })
      .eq("id", row.id);

    if (updateErr) throw new Error(updateErr.message);
    return { ok: true, discordUsername: row.discord_username } as const;
  });

/**
 * Fetch the current link record for a Clerk user.
 */
export const getMyLink = createServerFn({ method: "POST" })
  .inputValidator((input: { clerkUserId: string }) => input)
  .handler(async ({ data }) => {
    const { data: link } = await supabaseAdmin
      .from("discord_links")
      .select("*")
      .eq("clerk_user_id", data.clerkUserId)
      .maybeSingle();
    return { link };
  });

/**
 * Remove the link for a Clerk user.
 */
export const unlinkDiscord = createServerFn({ method: "POST" })
  .inputValidator((input: { clerkUserId: string }) => input)
  .handler(async ({ data }) => {
    const { error } = await supabaseAdmin
      .from("discord_links")
      .delete()
      .eq("clerk_user_id", data.clerkUserId);
    if (error) throw new Error(error.message);
    return { ok: true };
  });
