import { createServerFn } from "@tanstack/react-start";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

/**
 * Called by the dashboard when a user visits /dashboard/linking?token=...
 * The token was generated by the bot when the user ran /link or h!link.
 * This attaches the Clerk user ID to the pre-created row.
 */
export const claimBotToken = createServerFn({ method: "POST" })
  .inputValidator((input: { token: string; clerkUserId: string }) => {
    if (!input?.token || !input?.clerkUserId) throw new Error("token and clerkUserId are required");
    return input;
  })
  .handler(async ({ data }) => {
    console.log("[claimBotToken] token prefix:", data.token?.slice(0, 6), "user:", data.clerkUserId?.slice(0, 8));

    let row: Record<string, unknown> | null = null;
    try {
      const { data: found, error: fetchErr } = await supabaseAdmin
        .from("discord_links")
        .select("*")
        .eq("verification_code", data.token)
        .maybeSingle();

      if (fetchErr) {
        console.error("[claimBotToken] fetch error:", fetchErr.message, fetchErr.code);
        throw new Error(fetchErr.message);
      }
      row = found;
    } catch (e: any) {
      console.error("[claimBotToken] exception during fetch:", e?.message ?? e);
      throw e;
    }

    if (!row) {
      console.log("[claimBotToken] token not found in DB");
      return { ok: false, reason: "not_found" } as const;
    }
    if (row.verified) {
      console.log("[claimBotToken] token already used");
      return { ok: false, reason: "already_used" } as const;
    }
    if (row.expires_at && new Date(row.expires_at as string).getTime() < Date.now()) {
      console.log("[claimBotToken] token expired at", row.expires_at);
      return { ok: false, reason: "expired" } as const;
    }

    const { error: updateErr } = await supabaseAdmin
      .from("discord_links")
      .update({
        clerk_user_id: data.clerkUserId,
        verified: true,
        verification_code: null,
        expires_at: null,
        linked_at: new Date().toISOString(),
      })
      .eq("id", row.id as string);

    if (updateErr) {
      console.error("[claimBotToken] update error:", updateErr.message, updateErr.code);
      throw new Error(updateErr.message);
    }

    console.log("[claimBotToken] success, discord_username:", row.discord_username);
    return { ok: true, discordUsername: row.discord_username as string | null } as const;
  });

/**
 * Fetch the current link record for a Clerk user.
 */
export const getMyLink = createServerFn({ method: "POST" })
  .inputValidator((input: { clerkUserId: string }) => input)
  .handler(async ({ data }) => {
    const { data: link } = await supabaseAdmin
      .from("discord_links")
      .select("*")
      .eq("clerk_user_id", data.clerkUserId)
      .maybeSingle();
    return { link };
  });

/**
 * Remove the link for a Clerk user.
 */
export const unlinkDiscord = createServerFn({ method: "POST" })
  .inputValidator((input: { clerkUserId: string }) => input)
  .handler(async ({ data }) => {
    const { error } = await supabaseAdmin
      .from("discord_links")
      .delete()
      .eq("clerk_user_id", data.clerkUserId);
    if (error) throw new Error(error.message);
    return { ok: true };
  });
